services:
  app:
    build: .
    container_name: lms
    restart: always
    env_file:
      - conf/.env
    depends_on:
      - postgres
    networks:
      - lms_network

  postgres:
    container_name: lms-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: lms
      POSTGRES_PASSWORD: lms
    networks:
      - lms_network

networks:
  lms_network:
